# Generated by Django 5.0.6 on 2024-08-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('not_interesting', 'Not interesting'), ('success', 'Success'), ('call_back', 'Call back')], max_length=30)),
                ('name', models.CharField(max_length=300, verbose_name='Name parrents')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='age of child')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('phone_num', models.CharField(max_length=300, verbose_name='Phone number')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note of request')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Date of create')),
            ],
        ),
    ]
