# Generated by Django 5.0.6 on 2024-08-26 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0002_call_back_request_delete_homework'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Call_back_request',
            new_name='CallBackRequest',
        ),
    ]
