# Generated by Django 5.0.6 on 2024-07-07 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True, verbose_name='Name of course')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Course description')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='course/', verbose_name='Course image')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='date of create')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('Lesson_count', models.IntegerField(default=12, verbose_name='Count of lessons in course')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='user.moderatorprofile', verbose_name='Creator')),
            ],
        ),
        migrations.CreateModel(
            name='CourseMatherial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True, verbose_name='Name of material')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Material description')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='course/pdfs/', verbose_name='File')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='date of create')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='course.course', verbose_name='Course')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_materials', to='user.moderatorprofile', verbose_name='Creator')),
            ],
        ),
    ]
