# Generated by Django 5.0.6 on 2024-09-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=300, unique=True, verbose_name='Name of course'),
        ),
        migrations.AlterField(
            model_name='coursematherial',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Name of material'),
        ),
    ]
