# Generated by Django 5.0.6 on 2024-09-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_title_alter_coursematherial_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematherial',
            name='order_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order number'),
        ),
    ]
