# Generated by Django 5.0.6 on 2024-07-07 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True, verbose_name='Name of group')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Group description')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='Group/', verbose_name='Group image')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='date of create')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='user.moderatorprofile', verbose_name='Creator')),
                ('students', models.ManyToManyField(blank=True, related_name='group', to='user.studentprofile', verbose_name='Students')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True, verbose_name='Lesson title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Lesson description')),
                ('pdf_material', models.FileField(blank=True, null=True, upload_to='lessons/pdfs/', verbose_name='Lesson PDF Material')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Lesson Video URL')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Date of create')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course.course', verbose_name='Course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='user.teacherprofile', verbose_name='Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True, verbose_name='Homework title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Homework description')),
                ('due_date', models.DateTimeField(verbose_name='Due date')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Date of create')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='education.lesson', verbose_name='Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=True, verbose_name='Is present')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='user.studentprofile', verbose_name='Student')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='education.lesson', verbose_name='Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='LessonGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(verbose_name='Grade')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='education.lesson', verbose_name='Lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_grades', to='user.studentprofile', verbose_name='Student')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='submissions/', verbose_name='Submission file')),
                ('date_submitted', models.DateTimeField(auto_now_add=True, verbose_name='Date submitted')),
                ('grade', models.IntegerField(blank=True, null=True, verbose_name='Grade')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='education.homework', verbose_name='Homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='user.studentprofile', verbose_name='Student')),
            ],
        ),
    ]
