# Generated by Django 5.0.6 on 2024-07-10 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='grade_on_lesson',
            field=models.IntegerField(blank=True, null=True, verbose_name='lesson grade'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='grade_on_test',
            field=models.IntegerField(blank=True, null=True, verbose_name='lesson grade'),
        ),
        migrations.AddField(
            model_name='homework',
            name='homework_file',
            field=models.FileField(blank=True, null=True, upload_to='homeworks/files/', verbose_name='Lesson PDF Homework'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='course_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course.coursematherial', verbose_name='Material of lesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='education.group', verbose_name='Group'),
        ),
    ]
