# Generated by Django 5.0.6 on 2024-07-10 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('education', '0002_attendance_grade_on_lesson_attendance_grade_on_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course.coursematherial', verbose_name='Material of lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='education.group', verbose_name='Group'),
        ),
    ]
