# Generated by Django 5.0.6 on 2024-07-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_lesson_course_material_alter_lesson_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Lesson title'),
        ),
    ]
