# Generated by Django 5.0.6 on 2024-08-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_alter_homework_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lesson Date and Time'),
        ),
    ]
