# Generated by Django 5.0.6 on 2024-08-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_lesson_lesson_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_late',
            field=models.BooleanField(default=False, verbose_name='Is present'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='is_present',
            field=models.BooleanField(default=False, verbose_name='Is present'),
        ),
    ]
