# Generated by Django 5.0.6 on 2024-08-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_attendance_is_late_alter_attendance_is_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(blank=True, default=90, null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='is_late',
            field=models.BooleanField(default=False, verbose_name='Is late'),
        ),
    ]
