# Generated by Django 5.0.6 on 2024-08-23 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_lesson_duration_alter_attendance_is_late'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('lesson', 'student')},
        ),
    ]
