# Generated by Django 5.0.6 on 2024-08-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='comment_from_teacher',
            field=models.TextField(blank=True, null=True, verbose_name='Comment from teacher'),
        ),
    ]
