# Generated by Django 5.0.6 on 2024-09-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_submission_comment_from_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Lesson title'),
        ),
    ]
