# Generated by Django 5.0.6 on 2024-09-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, default='+38(066) 000 00 00', max_length=30, null=True),
        ),
    ]
