name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d test_db -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for database to be ready
      run: |
        echo "Waiting for database to be ready..."
        sleep 20
        for i in {1..30}; do
          if PGPASSWORD=postgres psql -h "localhost" -U "postgres" -d "test_db" -c '\q'; then
            echo "Postgres is up"
            break
          fi
          echo "Postgres is unavailable - sleeping"
          sleep 5
        done

    - name: Set environment variables
      run: echo "DJANGO_ALLOWED_HOSTS=localhost" >> $GITHUB_ENV

    - name: Run migrations
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
        DJANGO_ALLOWED_HOSTS: localhost
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: python manage.py migrate

    - name: Run tests
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
        DJANGO_ALLOWED_HOSTS: localhost
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: python manage.py test
